export const GET_BUSINESS_STATUS_LOADING = "GET_BUSINESS_STATUS_LOADING";
export const GET_BUSINESS_STATUS_SUCCESS = "GET_BUSINESS_STATUS_SUCCESS";
export const GET_BUSINESS_STATUS_FAILED = "GET_BUSINESS_STATUS_FAILED";

export const RESET_BUSINESS_STATUS = "RESET_BUSINESS_STATUS";

