export const KELUHAN_MASTER_PAIR = Object.freeze([
  {
    name: 'Aligner Full Set',
    aligners: [
      'Tidak Masuk',
      'Longgar',
      'Tajam',
      'Patah',
      'Hilang',
      'Tidak Sesuai/Tidak Lengkap',
      'Overdue Pengiriman',
      'Revisi',
      'Keluhan Medis',
    ],
  },
  {
    name: 'Aligner Lanjutan',
    aligners: [
      'Tidak Masuk',
      'Longgar',
      'Tajam',
      'Patah',
      'Hilang',
      'Tidak Sesuai',
      'Tidak Lengkap',
      'Overdue Pengiriman',
      'Revisi',
      'Keluhan Medis',
    ],
  },
  {
    name: 'Aligner Lanjutan',
    aligners: [
      'Tidak Masuk',
      'Longgar',
      'Tajam',
      'Patah',
      'Hilang',
      'Tidak Sesuai',
      'Tidak Lengkap',
      'Overdue Pengiriman',
      'Revisi',
      'Keluhan Medis',
    ],
  },
  {
    name: 'Aligner Rata10',
    aligners: [
      'Tidak Masuk',
      'Longgar',
      'Tajam',
      'Patah',
      'Hilang',
      'Tidak Sesuai',
      'Tidak Lengkap',
      'Overdue Pengiriman',
      'Revisi',
      'Keluhan Medis',
    ],
  },
  {
    name: 'Aligner Refinement',
    aligners: [
      'Tidak Masuk',
      'Longgar',
      'Tajam',
      'Patah',
      'Hilang',
      'Tidak Sesuai',
      'Tidak Lengkap',
      'Overdue Pengiriman',
      'Revisi',
      'Keluhan Medis',
    ],
  },
  {
    name: 'Aligner Set Pertama 3/3',
    aligners: [
      'Tidak Masuk',
      'Longgar',
      'Tajam',
      'Patah',
      'Hilang',
      'Tidak Sesuai',
      'Tidak Lengkap',
      'Overdue Pengiriman',
      'Revisi',
      'Keluhan Medis',
    ],
  },
  {
    name: 'Extra Aligner',
    aligners: ['Cetak Ulang', 'Overdue Pengiriman', 'Keluhan Medis'],
  },
  {
    name: 'Retainer',
    aligners: [
      'Tidak Masuk',
      'Longgar',
      'Tajam',
      'Patah',
      'Hilang',
      'Revisi',
      'Overdue Pengiriman',
      'Claim Free Retainer',
      'Keluhan Medis',
    ],
  },
]);
