export const config = {
    autofocus: true,
    toolbarAdaptive: false,
    // zIndex: 999,
    // readonly: false,
    // activeButtonsInReadOnly: ['source', 'fullsize', 'print', 'about'],
    // toolbarButtonSize: 'middle',
    // theme: 'default',
    // enableDragAndDropFileToEditor: true,
    // saveModeInCookie: false,
    // spellcheck: true,
    // editorCssClass: false,
    // triggerChangeEvent: true,
    height: 350,
    // direction: 'ltr',
    // language: 'en',
    // i18n: 'en',
    // tabIndex: -1,
    // // toolbar: true,
    // enter: 'P',
    // useSplitMode: false,
    // colorPickerDefaultTab: 'background',
    // imageDefaultWidth: 100,
    removeButtons: [
        'video',
        'source',
        'image',
        'fullsize',
        'about',
        'outdent',
        'indent',
        'print',
        'table',
        'fontsize',
        'superscript',
        'subscript',
        'file',
        'cut',
        'selectall',
    ],
    disablePlugins: ['paste', 'stat', 'image', 'video'],
    textIcons: false,
    uploader: {
        insertImageAsBase64URI: false,
    },
    placeholder: '',
    showXPathInStatusbar: false,
};
