export const GET_CLINIC_LOCATION_STATUS_LOADING = "GET_CLINIC_LOCATION_STATUS_LOADING";
export const GET_CLINIC_LOCATION_STATUS_SUCCESS = "GET_CLINIC_LOCATION_STATUS_SUCCESS";
export const GET_CLINIC_LOCATION_STATUS_FAILED = "GET_CLINIC_LOCATION_STATUS_FAILED";

export const RESET_CLINIC_LOCATION_STATUS = "RESET_CLINIC_LOCATION_STATUS";

