export const GET_TICKET_CATEGORIES_STATUS_LOADING = "GET_TICKET_CATEGORIES_STATUS_LOADING";
export const GET_TICKET_CATEGORIES_STATUS_SUCCESS = "GET_TICKET_CATEGORIES_STATUS_SUCCESS";
export const GET_TICKET_CATEGORIES_STATUS_FAILED = "GET_TICKET_CATEGORIES_STATUS_FAILED";

export const RESET_TICKET_CATEGORIES_STATUS = "RESET_TICKET_CATEGORIES_STATUS";

