// PATIENTS
export const GET_PATIENT_LIST = "GET_PATIENT_LIST";
export const GET_PATIENT_BY_PHONE = "GET_PATIENT_BY_PHONE";
export const UPDATE_PATIENT_TICKET_EXTRA = "UPDATE_PATIENT_TICKET_EXTRA";

// PATIENTS STATUS GET
export const GET_PATIENT_STATUS_LOADING = "GET_PATIENT_STATUS_LOADING";
export const GET_PATIENT_STATUS_SUCCESS = "GET_PATIENT_STATUS_SUCCESS";
export const GET_PATIENT_STATUS_FAILED = "GET_PATIENT_STATUS_FAILED";

// PATIENTS STATUS READ
export const READ_PATIENT_STATUS_LOADING = "READ_PATIENT_STATUS_LOADING";
export const READ_PATIENT_STATUS_SUCCESS = "READ_PATIENT_STATUS_SUCCESS";
export const READ_PATIENT_STATUS_FAILED = "READ_PATIENT_STATUS_FAILED";

// PATIENTS STATUS PATCH
export const PATCH_PATIENT_STATUS_LOADING = "PATCH_PATIENT_STATUS_LOADING";
export const PATCH_PATIENT_STATUS_SUCCESS = "PATCH_PATIENT_STATUS_SUCCESS";
export const PATCH_PATIENT_STATUS_FAILED = "PATCH_PATIENT_STATUS_FAILED";

// PATIENTS STATUS TICKET
export const GET_PATIENT_TICKET_STATUS_LOADING =
  "GET_PATIENT_TICKET_STATUS_LOADING";
export const GET_PATIENT_TICKET_STATUS_SUCCESS =
  "GET_PATIENT_TICKET_STATUS_SUCCESS";
export const GET_PATIENT_TICKET_STATUS_FAILED =
  "GET_PATIENT_TICKET_STATUS_FAILED";

// PATIENT STATUS TICKET RELATED
export const GET_PATIENT_TICKET_RELATED_LOADING =
  "GET_PATIENT_TICKET_RELATED_LOADING";
export const GET_PATIENT_TICKET_RELATED_SUCCESS =
  "GET_PATIENT_TICKET_RELATED_SUCCESS";
export const GET_PATIENT_TICKET_RELATED_FAILED =
  "GET_PATIENT_TICKET_RELATED_FAILED";

// PATIENTS STATUS HISTORY
export const GET_PATIENT_HISTORY_LOADING = "GET_PATIENT_HISTORY_LOADING";
export const GET_PATIENT_HISTORY_SUCCESS = "GET_PATIENT_HISTORY_SUCCESS";
export const GET_PATIENT_HISTORY_FAILED = "GET_PATIENT_HISTORY_FAILED";

// RESET ALL STATUS PATIENTS
export const RESET_PATIENT_STATUS = "RESET_PATIENT_STATUS";
