export const GET_CLINIC_REPORT_STATUS_LOADING = "GET_CLINIC_REPORT_STATUS_LOADING";
export const GET_CLINIC_REPORT_STATUS_SUCCESS = "GET_CLINIC_REPORT_STATUS_SUCCESS";
export const GET_CLINIC_REPORT_STATUS_FAILED = "GET_CLINIC_REPORT_STATUS_FAILED";

export const RESET_CLINIC_REPORT_STATUS = "RESET_CLINIC_REPORT_STATUS";
