//User
export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_BY_ID = "GET_USER_BY_ID";

//Component
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

//Role
export const GET_ROLE_LIST = "GET_ROLE_LIST";
export const GET_ROLE_BY_ID = "GET_ROLE_BY_ID";

//Team
export const GET_TEAM_BY_ID = "GET_TEAM_BY_ID";
export const GET_TEAM_LIST = "GET_TEAM_LIST";

//Ticket
export const GET_TICKET_BY_NUMBER = "GET_TICKET_BY_NUMBER";
export const GET_TICKET_LIST = "GET_TICKET_LIST";
export const GET_TICKET_HISTORY_LIST = "GET_TICKET_HISTORY_LIST";
export const GET_TICKET_COMMENT_LIST = "GET_TICKET_COMMENT_LIST";
export const GET_TICKET_RECENT_CLOSED = "GET_TICKET_RECENT_CLOSED";
export const GET_TICKET_SEARCH_INACTIVE = "GET_TICKET_SEARCH_INACTIVE";
export const GET_TICKET_SUMMARY_UNASSIGNED = "GET_TICKET_SUMMARY_UNASSIGNED";
export const GET_PATIENT_DETAILS_LIST = "GET_PATIENT_DETAILS_LIST";

//Report
export const GET_REPORT_DASHBOARD = "GET_REPORT_DASHBOARD";
export const GET_REPORT_DASHBOARD_BY_TYPE = "GET_REPORT_DASHBOARD_BY_TYPE";

//Category
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";

//Business
export const GET_BUSINESS_LIST = "GET_BUSINESS_LIST";

// Category Business
export const GET_CATEGORY_BUSINESS_STATUS_LOADING =
  "GET_CATEGORY_BUSINESS_STATUS_LOADING";
export const GET_CATEGORY_BUSINESS_STATUS_SUCCESS =
  "GET_CATEGORY_BUSINESS_STATUS_SUCCESS";
export const GET_CATEGORY_BUSINESS_STATUS_FAILED =
  "GET_CATEGORY_BUSINESS_STATUS_FAILED";
export const RESET_CATEGORY_BUSINESS_STATUS = "RESET_CATEGORY_BUSINESS_STATUS";

// CSAT
export const GET_CSAT_SUMMARY_LIST = "GET_CSAT_SUMMARY_LIST";
export const GET_TICKET_CSAT_LIST = "GET_TICKET_CSAT_LIST";
